displayName: Teapot Hacker Isolation
type: middleware
import: github.com/cdwiegand/teapot-hacker-isolation
basePkg: teapot_hacker_isolation
summary: 'Attackers who trigger backend 416 I'm a teapot responses can get blocked for a period of time.'
testData:
  minutesInJail: 2
  minInstances: 2
  returnCurrentStatusHeader: X-Teapot-Status
  returnCurrentCountHeader: X-Teapot-Count
  storageSystem: Memory
  loggingPrefix: "Teapot -> "
  triggerOnHeaders:
    - X-Hacker-Detected
  triggerOnStatusCodes:
    - 416
  blockedStatusCode: 416
