http:
  middlewares:
    teapot-hacker-isolation:
      plugin:
        teapot_hacker_isolation:
          minInstances: 2
          expirySeconds: 2
          returnCurrentStatusHeader: X-Teapot-Status
          returnCurrentCountHeader: X-Teapot-Count
          returnCurrentExpiresHeader: X-Teapot-Expires
          storageSystem: Redis
          redisHost: 127.0.0.1
          redisPort: 6379
          loggingPrefix: "Teapot -> "
          triggerOnHeaders: [ "X-Hacker-Detected" ]
          triggerOnStatusCodes: [ 418, 405 ]
          blockedStatusCode: 418
  routers:
    test:
      rule: "PathPrefix(`/`)"
      middlewares:
        - teapot-hacker-isolation
      service: api@internal
