http:
  middlewares:
    teapot-hacker-isolation:
      plugin:
        teapot_hacker_isolation:
          minutesInJail: 2
          minInstances: 2
          returnCurrentStatusHeader: X-Teapot-Status
          returnCurrentCountHeader: X-Teapot-Count
          storageSystem: Redis
          redis:
           - server: redis://@localhost:6379
          loggingPrefix: "Teapot -> "
          triggerOnHeaders:
            - X-Hacker-Detected
          triggerOnStatusCodes:
            - 416
          blockedStatusCode: 416
  routers:
    test:
      rule: "PathPrefix(`/`)"
      middlewares:
        - teapot-hacker-isolation
      service: api@internal
