http:
  middlewares:
    teapot-hacker-isolation:
      plugin:
        teapot_hacker_isolation:
          minInstances: 2
          minutesInJail: 2
          returnCurrentStatusHeader: X-Teapot-Status
          returnCurrentCountHeader: X-Teapot-Count
          storageSystem: Memory
          loggingPrefix: "Teapot -> "
          triggerOnHeaders: [ "X-Hacker-Detected" ]
          triggerOnStatusCodes: [ 418, 405 ]
          blockedStatusCode: 418
  routers:
    test:
      rule: "PathPrefix(`/`)"
      middlewares:
        - teapot-hacker-isolation
      service: api@internal
